### ISSUE TITLE
Add global config.yaml

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/joomlatools-console#12] opened 2016-04-15 08:38 UTC
Since the list of available options is getting a bit big, it would make life easier if we could store the settings in a config.yaml file.

**Comment by stevenrombauts** [comment] 2017-11-28 17:06
Related to #16

**Comment by stevenrombauts** [comment] 2021-01-20 07:29
Duplicate of #131

**Closed by stevenrombauts** 2021-01-20 07:29 UTC
